//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Input/Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace Titres
{
    public partial class @Controls : IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @Controls()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""Controls"",
    ""maps"": [
        {
            ""name"": ""PieceActions"",
            ""id"": ""c9c52495-4d22-437b-a204-e4accfe11d8b"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""0ab05233-daa2-42b1-b50c-b90557f99ba5"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Drop"",
                    ""type"": ""Button"",
                    ""id"": ""9a6998fe-66f9-448f-b26a-afe037d9cbd3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Rotate"",
                    ""type"": ""Value"",
                    ""id"": ""ea8f42c0-4677-40f9-af3e-aaf8503e5aa8"",
                    ""expectedControlType"": ""Integer"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""a389f43a-2ee5-45f9-b1ec-401895342fbe"",
                    ""path"": ""2DVector(mode=2)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""down"",
                    ""id"": ""7e28a6cc-7e57-49bc-8e56-a8825989cc85"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""68c050a9-6d27-47c9-83eb-3ca64f2b8eb8"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""5a4af385-0b39-4e02-9eb8-b18095f58d6e"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""e87e0ed0-a1df-4908-8524-20d36d2531b5"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""de69a269-8f8d-4531-bf21-391fe7dfc270"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""33354130-6f0c-427e-8b4e-0cb03576e1ca"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""cc7e2d6b-9e50-4319-9dc6-d88271e2769d"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Drop"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""5dd049a6-4cde-4aca-8e64-3c5787a511d0"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""345bb527-d1b9-441f-9bd0-de83c95da83a"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""3ed55fa0-f0f6-4449-be08-72150abcc163"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // PieceActions
            m_PieceActions = asset.FindActionMap("PieceActions", throwIfNotFound: true);
            m_PieceActions_Movement = m_PieceActions.FindAction("Movement", throwIfNotFound: true);
            m_PieceActions_Drop = m_PieceActions.FindAction("Drop", throwIfNotFound: true);
            m_PieceActions_Rotate = m_PieceActions.FindAction("Rotate", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }
        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }
        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // PieceActions
        private readonly InputActionMap m_PieceActions;
        private IPieceActionsActions m_PieceActionsActionsCallbackInterface;
        private readonly InputAction m_PieceActions_Movement;
        private readonly InputAction m_PieceActions_Drop;
        private readonly InputAction m_PieceActions_Rotate;
        public struct PieceActionsActions
        {
            private @Controls m_Wrapper;
            public PieceActionsActions(@Controls wrapper) { m_Wrapper = wrapper; }
            public InputAction @Movement => m_Wrapper.m_PieceActions_Movement;
            public InputAction @Drop => m_Wrapper.m_PieceActions_Drop;
            public InputAction @Rotate => m_Wrapper.m_PieceActions_Rotate;
            public InputActionMap Get() { return m_Wrapper.m_PieceActions; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(PieceActionsActions set) { return set.Get(); }
            public void SetCallbacks(IPieceActionsActions instance)
            {
                if (m_Wrapper.m_PieceActionsActionsCallbackInterface != null)
                {
                    @Movement.started -= m_Wrapper.m_PieceActionsActionsCallbackInterface.OnMovement;
                    @Movement.performed -= m_Wrapper.m_PieceActionsActionsCallbackInterface.OnMovement;
                    @Movement.canceled -= m_Wrapper.m_PieceActionsActionsCallbackInterface.OnMovement;
                    @Drop.started -= m_Wrapper.m_PieceActionsActionsCallbackInterface.OnDrop;
                    @Drop.performed -= m_Wrapper.m_PieceActionsActionsCallbackInterface.OnDrop;
                    @Drop.canceled -= m_Wrapper.m_PieceActionsActionsCallbackInterface.OnDrop;
                    @Rotate.started -= m_Wrapper.m_PieceActionsActionsCallbackInterface.OnRotate;
                    @Rotate.performed -= m_Wrapper.m_PieceActionsActionsCallbackInterface.OnRotate;
                    @Rotate.canceled -= m_Wrapper.m_PieceActionsActionsCallbackInterface.OnRotate;
                }
                m_Wrapper.m_PieceActionsActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @Movement.started += instance.OnMovement;
                    @Movement.performed += instance.OnMovement;
                    @Movement.canceled += instance.OnMovement;
                    @Drop.started += instance.OnDrop;
                    @Drop.performed += instance.OnDrop;
                    @Drop.canceled += instance.OnDrop;
                    @Rotate.started += instance.OnRotate;
                    @Rotate.performed += instance.OnRotate;
                    @Rotate.canceled += instance.OnRotate;
                }
            }
        }
        public PieceActionsActions @PieceActions => new PieceActionsActions(this);
        public interface IPieceActionsActions
        {
            void OnMovement(InputAction.CallbackContext context);
            void OnDrop(InputAction.CallbackContext context);
            void OnRotate(InputAction.CallbackContext context);
        }
    }
}
